### ISSUE TITLE
strange term `random.choices`

### ISSUE THREAD

**Issue by amiltonwong** [bfortuner/pytorch_tiramisu#1]
Hi, @bfortuner ,

I found a strange term `random.choices` in this [line](https://github.com/bfortuner/pytorch_tiramisu/blob/master/utils/training.py#L21). There is no random.choices ([link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.choice.html)) . Is it a typo or have special meaning?

**Comment by manuelhaussmann** [comment]
There is no `numpy.random.choices`, but there is a` random.choices`. See [link](https://docs.python.org/3/library/random.html#random.choices)

**Comment by ashr59** [comment]
It's written in Python 3.
Change that line to 
`return ''.join(random.choice(string.ascii_uppercase + string.digits))`
and run it via Python 2.

**Comment by raghavab1992** [comment]
random.choices is available in python 3.6. i think you can use random.sample instead. 
''.join(random.sample(string.ascii_uppercase + string.digits, k=n))
