### ISSUE TITLE
Need help for test.

### ISSUE THREAD

**Issue by CocoRLin** [bfortuner/pytorch_tiramisu#11]
Hello!
I'm new for neural network and pytorch!
When I run this code on my own dataset , I have confusion about ` test()` in `train.py`

1. I use `model.load_state_dict( torch.load('weights-100-0.018-0.065.pth'))
` to load parameters before `train_utils.test(model, test_loader, criterion, epoch=1)`  
but i have error like this:
`KeyError: 'unexpected key "startEpoch" in state_dict'`
2. How to use `latest.th`?

Thank you for your help!

**Comment by GWwangshuo** [comment]
@CocoRLin I encountered the same problem. Have you solved ? Thanks
