### ISSUE TITLE
Is there any details for how to train a model?

### ISSUE THREAD

**Issue by csjfwang** [bfortuner/pytorch_tiramisu#3]
hi @bfortuner ,
Is there any details for how to train a model? 
I tried but there is following error ,
```
python train_densenet_pytorch.py
Traceback (most recent call last):
  File "train_densenet_pytorch.py", line 25, in <module>
    import utils.training as train_utils
  File "/pytorch_tiramisu-master/utils/training.py", line 47, in <module>
    def train(epoch, net, trainLoader, optimizer, trainF, sessionName=get_rand_str(5)):
  File "/pytorch_tiramisu-master/utils/training.py", line 21, in get_rand_str
    return ''.join(random.choices(string.ascii_uppercase + string.digits, k=n))
AttributeError: 'module' object has no attribute 'choices'
```
Hope for your help.
Thanks a ton!

**Comment by raghavab1992** [comment]
hi @wlwsea  please checkout the other open issues! this issue has already been created.

**Comment by wlwsea** [comment]
hi @raghavab1992 ,
Thanks a lot! It really works.
I want to train and test this network on camvid dataset, but i don't know how to use it.
So , can you give me some advice or some details about my target?

Thx again!

**Comment by raghavab1992** [comment]
@wlwsea  im not really sure wht u mean by 'how to use it' but im gonna take a shot at it anyway. 
Please try to run the tiramisu-pytorch.ipynb notebook. Need to download camvid dataset and place it in the data folder(please look at the various folders present in github implementation and try to get an intuitive understanding of wht each folder might be for). It should be pretty straight forward from there.

**Comment by wlwsea** [comment]
@raghavab1992  
OK, i will try it.
Thanks a lot !

**Comment by bfortuner** [comment]
Updated the train.ipynb file with simpler interface. Hopefully that helps.
