### ISSUE TITLE
Results?

### ISSUE THREAD

**Issue by Faur** [bfortuner/pytorch_tiramisu#4]
What kind of results do you get? It would be really cool if you could post some learning curves, or even just the final mean IoU and accuracy on the camvid dataset for reference? :-)

**Comment by bfortuner** [comment]
Updated the README with our results. I believe the authors excluded the background class from their global accuracy calculation. If we do the same our results are close, but not matching their result.

**Comment by Faur** [comment]
The author does exclude the void class if that is what you mean

**Comment by Faur** [comment]
Is it possible to also include the mean intersection over union metric? I find it to be better for comparisons on these highly skewed datasets.
