### ISSUE TITLE
Take portion of tiramisu

### ISSUE THREAD

**Issue by varghesealex90** [bfortuner/pytorch_tiramisu#5]
Hi;

After training a tiramisu, I would like to just use all the layers till the bottleneck layer for feature extraction. Is there a good and recommended way to do it. ?

**Comment by bfortuner** [comment]
Yep! You can "cut" the model object after training like this to extract the feature maps you're looking for: 

https://github.com/bfortuner/pytorch-kaggle-starter/blob/master/models/builder.py#L40

the 'cut' param is the index of the layer
