### ISSUE TITLE
Can this be used for semantic segmentation?

### ISSUE THREAD

**Issue by mario98** [bfortuner/pytorch_tiramisu#7]
Although this repository claims to implement a paper about semantic segmentation, the code in this repository only does image classification based on the CIFAR dataset. Can this code actually be used for pixel-level semantic segmentation?

**Comment by raghavab1992** [comment]
@mario98  thats not correct! it does both! u can use densenet for classification and the tiramisu for pixel-level semantic segmentation

**Comment by bfortuner** [comment]
Yep! Just cleaned up the repo to focus on FCDenseNet and moved helpers to files.
